<?php
$z[0]=Array("global","",76,102);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",603,635);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("include","",790,825);
$z[2][4]['filename']="head.htm";
$z[3]=Array("list","\r\n            <div class=\"list_article_div\">\r\n                <p class=\"list_article_p1\">➣&nbsp;&nbsp;<a href=\"[field:arcurl/]\">[field:title/]</a></p>\r\n                <p class=\"list_article_p2\">[field:pubdate function=\"MyDate('Y-m-d ',@me)\" /]</p>\r\n            </div>\r\n			",981,1293);
$z[3][4]['pagesize']="10";
$z[4]=Array("include","",1329,1366);
$z[4][4]['filename']="footer.htm";

?>